{"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decapsulationKeyInconsistent","kind":"identifier"}],"modules":[{"name":"SwiftKyber"}],"title":"KyberException.decapsulationKeyInconsistent","roleHeading":"Case","externalID":"s:10SwiftKyber0B9ExceptionO28decapsulationKeyInconsistentyA2CmF","symbolKind":"case","role":"symbol"},"abstract":[{"text":"Inconsistent decapsulation key data","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/KyberException\/decapsulationKeyInconsistent"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftkyber\/kyberexception\/decapsulationkeyinconsistent"]}],"hierarchy":{"paths":[["doc:\/\/SwiftKyber\/documentation\/SwiftKyber","doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/KyberException"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"decapsulationKeyInconsistent","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://SwiftKyber/documentation/SwiftKyber/KyberException/decapsulationKeyInconsistent":{"kind":"symbol","title":"KyberException.decapsulationKeyInconsistent","identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/KyberException\/decapsulationKeyInconsistent","abstract":[{"type":"text","text":"Inconsistent decapsulation key data"}],"url":"\/documentation\/swiftkyber\/kyberexception\/decapsulationkeyinconsistent","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decapsulationKeyInconsistent","kind":"identifier"}],"type":"topic"},"doc://SwiftKyber/documentation/SwiftKyber":{"type":"topic","abstract":[{"text":"Module-Lattice-based Key-Encapsulation Mechanism Standard","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/swiftkyber","title":"SwiftKyber","identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber"},"doc://SwiftKyber/documentation/SwiftKyber/KyberException":{"abstract":[{"text":"The Kyber exceptions","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"KyberException","kind":"identifier"}],"identifier":"doc:\/\/SwiftKyber\/documentation\/SwiftKyber\/KyberException","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KyberException"}],"type":"topic","url":"\/documentation\/swiftkyber\/kyberexception","title":"KyberException"}}}